name: Linting

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Setup env
        run: echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" > .env

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        with:
          version: 8

      - name: Install dependencies
        run: pnpm install
        shell: bash

      - name: Run Eslint
        run: pnpm run lint
        shell: bash
