name: Linting

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  cache-and-install:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        with:
          version: 8

      - name: Install dependencies
        run: pnpm install

      - name: Run Eslint
        run: pnpm run lint
